### ISSUE TITLE
/kitty-spring-cloud-starter/kitty-spring-cloud-starter-web/src/main/java/com/cxytiandi/kitty/web/autoconfigure/WebAutoConfiguration.java:[18,2] 找不到符号

### ISSUE THREAD

**Issue by hadesvip** [yinjihuan/kitty#3]
问题描述如下图
![Uploading image.png…]()

**Comment by hadesvip** [comment]
![image](https://user-images.githubusercontent.com/9640832/76158548-d7dc3680-6151-11ea-98ef-6fa2fb363c1f.png)

**Comment by hadesvip** [comment]
![image](https://user-images.githubusercontent.com/9640832/76158554-f2aeab00-6151-11ea-9d2a-e917d46d2c88.png)

**Comment by yinjihuan** [comment]
你应该是Cat的客户端没下载下来，现在比较尴尬的是Cat的新版本客户端3.0没有上传到中央仓库，我是用的另一个仓库的，如果下载下来不能加载的话可以从Cat的Github上下载编译好的jar放到本地目录，或者用源码打包。

https://github.com/dianping/cat/blob/master/lib/java/README.zh-CN.md

lib目录下有编译好了的jar。

**Comment by hadesvip** [comment]
@yinjihuan  按照上述步骤解决了，谢谢
